AzureML/AzureML/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AzureML.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

AzureML/AzureML/Controllers/RecommendationController.cs
namespace AzureML.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    using Newtonsoft.Json;

    public class RecommendationController : Controller
    {
        public ActionResult Index()
        {
            return this.View();
        }

        // GET: Recommendation
        public async Task<ActionResult> Get( string id )
        {
            if( string.IsNullOrWhiteSpace( id ) )
            {
                return this.RedirectToAction( "Index" );
            }

            var result = await InvokeRecommenderService( id );
            return this.View( result );
        }

        private static async Task<List<List<string>>> InvokeRecommenderService(
            string userId)
        {
            using (var client = new HttpClient())
            {
                var scoreData = new ScoreData
                                    {
                                        FeatureVector = new Dictionary<string, string> {{ "userID", userId }},
                                        GlobalParameters =
                                            new Dictionary<string, string>
                                                {
                                                    {
                                                        "Maximum number of items to recommend to a user",
                                                        "5"
                                                    },
                                                }
                                    };

                var scoreRequest = new ScoreRequest { Id = "score00001", Instance = scoreData };

                #region API KEY
                const string apiKey = "NotARealKey"; // Replace this with the API key for the web service
                #endregion

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);

                client.BaseAddress =
                    new Uri(
                        "https://ussouthcentral.services.azureml.net/workspaces/b283a38bc4d94a5ca304b8827468734e/services/f1ff9c78f28e43e7930dc39fc7bce318/scoremultirow");
                var response = await client.PostAsJsonAsync(string.Empty, scoreRequest);
                if (response.IsSuccessStatusCode)
                {
                    var result = await response.Content.ReadAsStringAsync();
                    return JsonConvert.DeserializeObject<List<List<string>>>(result);
                }
                
                throw new InvalidOperationException();
            }
        }
    }

    public class ScoreRequest
    {
        public string Id { get; set; }

        public ScoreData Instance { get; set; }
    }

    public class ScoreData
    {
        public Dictionary<string, string> FeatureVector { get; set; }

        public Dictionary<string, string> GlobalParameters { get; set; }
    }
}

AzureML/AzureML/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AzureML/AzureML/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AzureML/AzureML/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AzureML/AzureML/Views/Recommendation/Get.cshtml
@model List<List<string>>

@{
    ViewBag.Title = "Get";
}

<h2>Recommendations (@Model.Count)</h2>

<div>
    <hr />
    @for( int i = 0; i < Model.Count; i++ )
    {
        var rec = Model[ i ];
        <div>
            <h4>Recommendation # @(i + 1)</h4>
            <ul>
                <li>User: @rec[0]</li>
                <li>Place ID: @rec[ 1 ]</li>
                <li>Lat: @rec[ 2 ]</li>
                <li>Long: @rec[ 3 ]</li>
                <li>Name: @rec[ 4 ]</li>
                <li>Address: @rec[ 5 ]</li>
                <li>City: @rec[ 6 ]</li>
                <li>State: @rec[ 7 ]</li>
                <li>Country: @rec[ 8 ]</li>
                <li>Zip: @rec[ 9 ]</li>
                <li>Alcohol: @rec[ 10 ]</li>
                <li>Smoking: @rec[ 11 ]</li>
                <li>Dress Code: @rec[ 12 ]</li>
                <li>Accessibility: @rec[ 13 ]</li>
                <li>Price: @rec[ 14 ]</li>
                <li>Url: @rec[ 15 ]</li>
                <li>Ambience: @rec[ 16 ]</li>
                <li>Franchise: @rec[ 17 ]</li>
                <li>Area: @rec[ 18 ]</li>
                <li>Othe Services: @rec[ 19 ]</li>
            </ul>
        </div>
    }
</div>

AzureML/AzureML/Views/Recommendation/Index.cshtml
@{
    ViewBag.Title = "Input";
}

<h2>Input</h2>
@using (Html.BeginForm("Get", "Recommendation", FormMethod.Get))
{
    <div class="row">
        <label>User ID</label>
        @Html.DropDownList("id", new SelectList(Data.Users))
    </div>
    <div class="row">
        <input type="submit" value="Get Recommendations" class="btn btn-primary btn-lg" />
    </div>
}

AzureML/AzureML/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Recommendations", "Index", "Recommendation")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>